---
language: objective-c
cache: cocoapods
sudo: false

before_install:
 - gem install activesupport
 - gem install cocoapods xcpretty

script:
 - xcodebuild -workspace Santa.xcworkspace -scheme All -derivedDataPath build build test CODE_SIGN_IDENTITY='' | xcpretty -sc && exit ${PIPESTATUS[0]}
